### ISSUE TITLE
Add more doc on server dashboard and server/user management

### ISSUE THREAD

**Issue by pierrepo** [plasmabio/plasma#121]
The server dashboard is convenient to display server currently running:

![image](https://user-images.githubusercontent.com/733861/79741853-3c1e1880-8302-11ea-956c-d0e3059fc9b1.png)

The doc could be enhanced (or linked to existing one) with regards to these questions items.

## User management

What the "Add User" button exactly means? Does it create a user on the host on solely on the Jupyter Hub? What could be the user case?

The "edit user" button sets (or unsets) a given user "admin" i.e. the capability to create and remove environments. Maybe there could be a link to the doc: https://docs.plasmabio.org/en/latest/install/admins.html to tell that admin users could be define either with the command line (and ansible), either graphically on the server dashboard (but at least one admin user must exist).

What does the "delete user" do exactly? Is the user deleted from the hub or from the system?

## Server management

The "stop server" button is OK.

What is the user case of the "start server" button? Are listed servers available of start (of restarts), servers stopped and not yet culled?

**Comment by jtpio** [comment]
This sounds like most of the answers to these questions could belong to the upstream documentation:

https://jupyterhub.readthedocs.io/en/latest/getting-started/authenticators-users-basics.html#add-or-remove-users-from-the-hub

However it could be tricky to make a generic explanation as most of the components could be swapped (spawner and authenticator).

Also since PlasmaBio makes some opinionated choices when it comes to the authentication and user environments, we could decide to override more parts of the base admin page. For example by removing unnecessary buttons to prevent confusion.

> What the "Add User" button exactly means? Does it create a user on the host on solely on the Jupyter Hub? What could be the user case?

It can create users on the host. But for now it is not enabled:

![image](https://user-images.githubusercontent.com/591645/79745680-07fa2600-8309-11ea-99d6-3ead4f7c9dc7.png)


> The "edit user" button sets (or unsets) a given user "admin" i.e. the capability to create and remove environments. Maybe there could be a link to the doc: https://docs.plasmabio.org/en/latest/install/admins.html to tell that admin users could be define either with the command line (and ansible), either graphically on the server dashboard (but at least one admin user must exist).

Sounds good :+1: 

> What does the "delete user" do exactly? Is the user deleted from the hub or from the system?

It removes the user from the hub database. But the user still exists on the host.

> What is the user case of the "start server" button?

Admins can start user servers to be able to access them afterward. It can be sometimes be useful for debugging issues. But in our case this could indeed be confusing as the spawn process asks the user to choose an image. 
Do you think it would be better to hide the button?

**Comment by jtpio** [comment]
@pierrepo do you think we should keep this one open?

Or similar to https://github.com/plasmabio/plasma/issues/129, we could close it and open an issue on the JupyterHub repo.

**Comment by pierrepo** [comment]
Indeed. There's no need to keep this one open here.
