### ISSUE TITLE
Add search box in server admin panel

### ISSUE THREAD

**Issue by pierrepo** [plasmabio/plasma#129]
Jupyter Hub admins can list, stop and start "servers" from the admin panel:
![image](https://user-images.githubusercontent.com/733861/79889860-e713fc80-83fe-11ea-9e57-d7b41e025e46.png)

Columns can be sorted alphabetically and in reversed order.

Since, PlasmaBio might hold several dozen servers, it would be nice to have a search box to filter out rows. For instance:
https://www.w3schools.com/bootstrap/bootstrap_filters.asp
https://examples.bootstrap-table.com/#welcomes/from-html.html

**Comment by jtpio** [comment]
That sounds like a nice-to-have. Maybe even for JupyterHub in general actually.

**Comment by pierrepo** [comment]
Totally agree. It could be an upstream feature.

**Comment by jtpio** [comment]
For reference, there is ongoing work to add pagination to the admin panel in https://github.com/jupyterhub/jupyterhub/pull/2929.

This might conflict with the idea of having a search box of the pagination is done server side.

**Comment by jtpio** [comment]
We discussed this issue today with @pierrepo.

It is indeed more about JupyterHub itself (since it relates to the admin page), but not really specific to Plasma.

So let's close this issue. @pierrepo feel free to open a new one on the JupyterHub repo if you think it is still relevant (considering that the pagination PR has now been merged)
